# secrets.toml

# Sua chave da API OpenAI
OPENAI_API_KEY = "Sua API key da OpenAI"

# Assistant OpenAI
OPENAI_ASSISTANT = "Búmero da assistente OpenAI"

# Sua chave da API ElevenLabs
ELEVEN_LABS_API_KEY = "API key da Eleven Labs"

